// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package bucket

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ObjectManifest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{171}); err != nil {
		return err
	}

	// t.Body (bucket.Body) (struct)
	if len("b") > 1000000 {
		return xerrors.Errorf("Value in field \"b\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("b"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("b")); err != nil {
		return err
	}

	if err := t.Body.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ETag (string) (string)
	if len("e") > 1000000 {
		return xerrors.Errorf("Value in field \"e\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("e"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("e")); err != nil {
		return err
	}

	if len(t.ETag) > 1000000 {
		return xerrors.Errorf("Value in field t.ETag was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.ETag))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.ETag)); err != nil {
		return err
	}

	// t.Key (string) (string)
	if len("k") > 1000000 {
		return xerrors.Errorf("Value in field \"k\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("k"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("k")); err != nil {
		return err
	}

	if len(t.Key) > 1000000 {
		return xerrors.Errorf("Value in field t.Key was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Key))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Key)); err != nil {
		return err
	}

	// t.Created (int64) (int64)
	if len("t") > 1000000 {
		return xerrors.Errorf("Value in field \"t\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("t"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("t")); err != nil {
		return err
	}

	if t.Created >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Created)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Created-1)); err != nil {
			return err
		}
	}

	// t.CacheControl (string) (string)
	if len("cc") > 1000000 {
		return xerrors.Errorf("Value in field \"cc\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cc"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("cc")); err != nil {
		return err
	}

	if len(t.CacheControl) > 1000000 {
		return xerrors.Errorf("Value in field t.CacheControl was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.CacheControl))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.CacheControl)); err != nil {
		return err
	}

	// t.ContentDisposition (string) (string)
	if len("cd") > 1000000 {
		return xerrors.Errorf("Value in field \"cd\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cd"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("cd")); err != nil {
		return err
	}

	if len(t.ContentDisposition) > 1000000 {
		return xerrors.Errorf("Value in field t.ContentDisposition was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.ContentDisposition))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.ContentDisposition)); err != nil {
		return err
	}

	// t.ContentEncoding (string) (string)
	if len("ce") > 1000000 {
		return xerrors.Errorf("Value in field \"ce\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ce"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("ce")); err != nil {
		return err
	}

	if len(t.ContentEncoding) > 1000000 {
		return xerrors.Errorf("Value in field t.ContentEncoding was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.ContentEncoding))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.ContentEncoding)); err != nil {
		return err
	}

	// t.ContentLanguage (string) (string)
	if len("cl") > 1000000 {
		return xerrors.Errorf("Value in field \"cl\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cl"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("cl")); err != nil {
		return err
	}

	if len(t.ContentLanguage) > 1000000 {
		return xerrors.Errorf("Value in field t.ContentLanguage was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.ContentLanguage))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.ContentLanguage)); err != nil {
		return err
	}

	// t.ContentType (string) (string)
	if len("ct") > 1000000 {
		return xerrors.Errorf("Value in field \"ct\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ct"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("ct")); err != nil {
		return err
	}

	if len(t.ContentType) > 1000000 {
		return xerrors.Errorf("Value in field t.ContentType was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.ContentType))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.ContentType)); err != nil {
		return err
	}

	// t.DeleteMarker (bool) (bool)
	if len("dm") > 1000000 {
		return xerrors.Errorf("Value in field \"dm\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("dm"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("dm")); err != nil {
		return err
	}

	if err := cbg.WriteBool(w, t.DeleteMarker); err != nil {
		return err
	}

	// t.Metadata (map[string]string) (map)
	if len("md") > 1000000 {
		return xerrors.Errorf("Value in field \"md\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("md"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("md")); err != nil {
		return err
	}

	{
		if len(t.Metadata) > 4096 {
			return xerrors.Errorf("cannot marshal t.Metadata map too large")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajMap, uint64(len(t.Metadata))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.Metadata))
		for k := range t.Metadata {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.Metadata[k]

			if len(k) > 1000000 {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(k)); err != nil {
				return err
			}

			if len(v) > 1000000 {
				return xerrors.Errorf("Value in field v was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(v))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(v)); err != nil {
				return err
			}

		}
	}
	return nil
}

func (t *ObjectManifest) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ObjectManifest{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ObjectManifest: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 2)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 1000000)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Body (bucket.Body) (struct)
		case "b":

			{

				if err := t.Body.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Body: %w", err)
				}

			}
			// t.ETag (string) (string)
		case "e":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.ETag = string(sval)
			}
			// t.Key (string) (string)
		case "k":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.Key = string(sval)
			}
			// t.Created (int64) (int64)
		case "t":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.Created = int64(extraI)
			}
			// t.CacheControl (string) (string)
		case "cc":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.CacheControl = string(sval)
			}
			// t.ContentDisposition (string) (string)
		case "cd":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.ContentDisposition = string(sval)
			}
			// t.ContentEncoding (string) (string)
		case "ce":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.ContentEncoding = string(sval)
			}
			// t.ContentLanguage (string) (string)
		case "cl":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.ContentLanguage = string(sval)
			}
			// t.ContentType (string) (string)
		case "ct":

			{
				sval, err := cbg.ReadStringWithMax(cr, 1000000)
				if err != nil {
					return err
				}

				t.ContentType = string(sval)
			}
			// t.DeleteMarker (bool) (bool)
		case "dm":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajOther {
				return fmt.Errorf("booleans must be major type 7")
			}
			switch extra {
			case 20:
				t.DeleteMarker = false
			case 21:
				t.DeleteMarker = true
			default:
				return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
			}
			// t.Metadata (map[string]string) (map)
		case "md":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajMap {
				return fmt.Errorf("expected a map (major type 5)")
			}
			if extra > 4096 {
				return fmt.Errorf("t.Metadata: map too large")
			}

			t.Metadata = make(map[string]string, extra)

			for i, l := 0, int(extra); i < l; i++ {

				var k string

				{
					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					k = string(sval)
				}

				var v string

				{
					sval, err := cbg.ReadStringWithMax(cr, 1000000)
					if err != nil {
						return err
					}

					v = string(sval)
				}

				t.Metadata[k] = v

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *Body) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{165}); err != nil {
		return err
	}

	// t.SHA256 ([]uint8) (slice)
	if len("h") > 1000000 {
		return xerrors.Errorf("Value in field \"h\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("h"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("h")); err != nil {
		return err
	}

	if len(t.SHA256) > 2097152 {
		return xerrors.Errorf("Byte array in field t.SHA256 was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.SHA256))); err != nil {
		return err
	}

	if _, err := cw.Write(t.SHA256); err != nil {
		return err
	}

	// t.MD5 ([]uint8) (slice)
	if len("m") > 1000000 {
		return xerrors.Errorf("Value in field \"m\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("m"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("m")); err != nil {
		return err
	}

	if len(t.MD5) > 2097152 {
		return xerrors.Errorf("Byte array in field t.MD5 was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.MD5))); err != nil {
		return err
	}

	if _, err := cw.Write(t.MD5); err != nil {
		return err
	}

	// t.Size (int64) (int64)
	if len("s") > 1000000 {
		return xerrors.Errorf("Value in field \"s\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("s"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("s")); err != nil {
		return err
	}

	if t.Size >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Size)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Size-1)); err != nil {
			return err
		}
	}

	// t.Blobs ([]bucket.BlobRef) (slice)
	if len("bl") > 1000000 {
		return xerrors.Errorf("Value in field \"bl\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("bl"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("bl")); err != nil {
		return err
	}

	if len(t.Blobs) > 8192 {
		return xerrors.Errorf("Slice value in field t.Blobs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Blobs))); err != nil {
		return err
	}
	for _, v := range t.Blobs {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.IndexRoot (cid.Cid) (struct)
	if len("ir") > 1000000 {
		return xerrors.Errorf("Value in field \"ir\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ir"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("ir")); err != nil {
		return err
	}

	if t.IndexRoot == nil {
		if _, err := cw.Write(cbg.CborNull); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteCid(cw, *t.IndexRoot); err != nil {
			return xerrors.Errorf("failed to write cid field t.IndexRoot: %w", err)
		}
	}

	return nil
}

func (t *Body) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Body{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Body: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 2)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 1000000)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.SHA256 ([]uint8) (slice)
		case "h":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.SHA256: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.SHA256 = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.SHA256); err != nil {
				return err
			}

			// t.MD5 ([]uint8) (slice)
		case "m":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.MD5: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.MD5 = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.MD5); err != nil {
				return err
			}

			// t.Size (int64) (int64)
		case "s":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.Size = int64(extraI)
			}
			// t.Blobs ([]bucket.BlobRef) (slice)
		case "bl":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Blobs: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Blobs = make([]BlobRef, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Blobs[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Blobs[i]: %w", err)
						}

					}

				}
			}
			// t.IndexRoot (cid.Cid) (struct)
		case "ir":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					c, err := cbg.ReadCid(cr)
					if err != nil {
						return xerrors.Errorf("failed to read cid field t.IndexRoot: %w", err)
					}

					t.IndexRoot = &c
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *BlobRef) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Digest ([]uint8) (slice)
	if len("d") > 1000000 {
		return xerrors.Errorf("Value in field \"d\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("d"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("d")); err != nil {
		return err
	}

	if len(t.Digest) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Digest was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Digest))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Digest); err != nil {
		return err
	}

	// t.Length (int64) (int64)
	if len("l") > 1000000 {
		return xerrors.Errorf("Value in field \"l\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("l"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("l")); err != nil {
		return err
	}

	if t.Length >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Length)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Length-1)); err != nil {
			return err
		}
	}

	// t.Offset (int64) (int64)
	if len("o") > 1000000 {
		return xerrors.Errorf("Value in field \"o\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("o"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("o")); err != nil {
		return err
	}

	if t.Offset >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Offset)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Offset-1)); err != nil {
			return err
		}
	}

	return nil
}

func (t *BlobRef) UnmarshalCBOR(r io.Reader) (err error) {
	*t = BlobRef{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("BlobRef: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 1)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 1000000)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Digest ([]uint8) (slice)
		case "d":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Digest: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Digest = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Digest); err != nil {
				return err
			}

			// t.Length (int64) (int64)
		case "l":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.Length = int64(extraI)
			}
			// t.Offset (int64) (int64)
		case "o":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.Offset = int64(extraI)
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
